WITH t AS (
    SELECT
        to_number(a.experiment_id)                  AS experiment_id,
        a.created_date,
        b.slope,
        b.ic50 / 1000000                            AS ic50_m,
        b.ic50 * 1000                               AS ic50_nm,
        b.min,
        b.max,
        b.z_prime,
        b.low_avg,
        b.high_avg,
        b.plate_number,
        c.substrate_lot,
       
        c.antibody_lot,
        c.reagent_lot,
        c.info_target as target,
        c.tracer,
        c.plasma_concentration as Plasma_conc,
        'TR-FRET'                                   AS assay_type,
        substr(d.formatted_batch_id, 1, 10)         AS formatted_id,
        d.reg_id,
        d.supplier_ref,
        
        d.formatted_batch_id,
        b.max - b.min                               AS span,
        'in house'                                  AS site,
        c.target_conc,
        c.tracer_conc,
        c.cofactor,
        c.cofactor_conc,
        c.incubation_time,
        c.pre_incubation_time,
        c.antibody,
        c.substrate,
        c.substrate_conc,
		c.cells_well,
        to_number(c.n_replicate)                    AS n,
        b.max_response,
        b.absolute_ic50,
        b.absolute_ic50 * 1000                      AS absolute_ic50_nm,
        b.highest_concentration,
        b.response_at_hc,
        b.compound_status,
		b.classification
    FROM
             studies_summary a
        INNER JOIN ic50_new_results_summary  b ON a.experiment_id = b.experiment_id
        INNER JOIN TM_PROTOCOL_PROPS_PIVOT             c ON b.experiment_id = c.experiment_id
        INNER JOIN c$pinpoint.reg_batches    d ON b.id = d.formatted_batch_id
    WHERE
        c.protocol_id IN ( 543 )
)
SELECT
    t.experiment_id,
    t.created_date,
    t.slope,
    t.ic50_m,
    t.ic50_nm,
    t.min,
    t.max,
    round(AVG(z_prime), 4) AS z_prime,
    t.high_avg,
    t.low_avg,
    t.plate_number,
    t.substrate_lot,
  t.cells_well,
    t.antibody_lot,
    t.reagent_lot,
    t.target,
    t.tracer,
    t.plasma_conc,
    t.assay_type,
    t.formatted_id,
    t.reg_id,
    t.supplier_ref,
    
    t.formatted_batch_id,
    t.span,
    t.site,
    t.target_conc,
    t.tracer_conc,
    t.cofactor,
    t.cofactor_conc,
    t.incubation_time,
    t.pre_incubation_time,
    t.antibody,
    t.substrate,
    t.substrate_conc,
    t.n,
    t.max_response,
    t.absolute_ic50,
    t.absolute_ic50_nm,
    t.highest_concentration,
    t.response_at_hc,
    t.compound_status,
	t.classification
FROM
    t
    join c$pinpoint.reg_data a on t.formatted_id=a.formatted_id
    join JAK2_SUMMARY_VW b on a.formatted_id=b.formatted_id
GROUP BY
    t.experiment_id,
    t.created_date,
    t.slope,
    t.ic50_m,
    t.ic50_nm,
    t.min,
    t.max,
    t.high_avg,
    t.low_avg,
    t.plate_number,
    t.substrate_lot,
  t.cells_well,
    t.antibody_lot,
    t.reagent_lot,
    t.target,
    t.tracer,
    t.plasma_conc,
    t.assay_type,
    t.formatted_id,
    t.reg_id,
    t.supplier_ref,
    
    t.formatted_batch_id,
    t.span,
    t.site,
    t.target_conc,
    t.tracer_conc,
    t.cofactor,
    t.cofactor_conc,
    t.incubation_time,
    t.pre_incubation_time,
    t.antibody,
    t.substrate,
    t.substrate_conc,
    t.n,
    t.max_response,
    t.absolute_ic50,
    t.absolute_ic50_nm,
    t.highest_concentration,
    t.response_at_hc,
    t.compound_status,
	t.classification
