Study Summary:TALL,select a.protocol||':'||a.protocol_id "Protocol",a.descr "Description",(select pref_name||' '||lastname from gateway.ROLES_NONTP_PERSONNEL where isid=upper(b.isid))||' ('||b.isid||')' "Creator",nvl(to_char(b.CREATED_DATE,'-DATEFORMAT- HH24:MI:SS'), '') "Created", nvl(to_char(b.COMPLETED_DATE,'-DATEFORMAT- HH24:MI:SS'), '') "Completed",'-USERFIRST- -USERLAST- (-USER-)' "Counter-signer",to_char(sysdate,'-DATEFORMAT- HH24:MI:SS') "Countersigned" from DS3_USERDATA.TM_PROTOCOLS a, DS3_USERDATA.TM_experiments b where a.protocol_id=b.protocol_id  and b.experiment_id=?


_DOTSPLIT_Results:NORMAL,
SELECT * FROM (SELECT P.PLATE_NUMBER as Plate_No ,T3.DISPLAY_NAME AS ID , 
 R.MOLFILE AS STRUCTURES ,
t8.COMPOUND_STATUS||t8.IC50_RR AS RELATIVE_IC50,
ROUND(T8.ABSOLUTE_IC50,4) ABSOLUTE_IC50,
ROUND(T8.MAX_RESPONSE,4) AS "% MAX RESPONSE",
ROUND(T8.RESPONSE_AT_HC,4) AS "% RESPONSE @HC",
T8.HIGHEST_CONCENTRATION AS "HIGHEST CONCENTRATION (uM)", 
T7.DATA AS GRAPH ,
  T5.LABEL        AS CLASSIFICATION,
CASE T1.status
    WHEN 1
    THEN 'VALIDATED'
    WHEN 2
    THEN 'INVALIDATED'
    WHEN 3
    THEN 'PUBLISHED'
    ELSE 'NOT VALIDATED'
  END STATUS   
FROM DS3_USERDATA.SU_ANALYSIS_RESULTS T1 ,
  DS3_USERDATA.SU_GROUPINGS T2 ,
  DS3_USERDATA.SU_SAMPLES T3 ,
  DS3_USERDATA.SU_CLASSIFICATION_RULES T5 ,
  DS3_USERDATA.SU_ANALYSIS_LAYERS T6 ,
  DS3_USERDATA.SU_CHARTS T7,
  DS3_USERDATA.IC50_NEW_RESULTS_SUMMARY T8,
  C$PINPOINT.REG_DATA R,
DS3_USERDATA.SU_PLATES P
WHERE T1.LAYER_ID    = T6.ID
AND T1.RULE_ID       = T5.ID
AND T1.GROUP_ID      = T2.ID
AND T2.SAMPLE_ID  = T3.ID
AND T7.RESULT_ID     = T1.ID
AND R.FORMATTED_ID = substr(T3.display_name,1,10)
AND P.PLATE_SET=T2.PLATE_SET
AND P.EXPERIMENT_ID=T2.EXPERIMENT_ID
AND T3.DISPLAY_NAME = T8.ID
AND T2.EXPERIMENT_ID=T8.EXPERIMENT_ID
AND P.PLATE_NUMBER=T8.PLATE_NUMBER
AND T2.EXPERIMENT_ID=?


UNION ALL

SELECT P.PLATE_NUMBER as Plate_No ,T3.DISPLAY_NAME AS ID , 
S.MOLFILE AS STRUCTURES,
t8.COMPOUND_STATUS||t8.IC50_RR AS RELATIVE_IC50,
ROUND(T8.ABSOLUTE_IC50,4) ABSOLUTE_IC50,
ROUND(T8.MAX_RESPONSE,4) AS "% MAX RESPONSE",
ROUND(T8.RESPONSE_AT_HC,4) AS "% RESPONSE @HC",
T8.HIGHEST_CONCENTRATION AS "HIGHEST CONCENTRATION (uM)", 
T7.DATA AS GRAPH ,
  T5.LABEL        AS CLASSIFICATION,
CASE T1.status
    WHEN 1
    THEN 'VALIDATED'
    WHEN 2
    THEN 'INVALIDATED'
    WHEN 3
    THEN 'PUBLISHED'
    ELSE 'NOT VALIDATED'
  END STATUS   
FROM DS3_USERDATA.SU_ANALYSIS_RESULTS T1 ,
  DS3_USERDATA.SU_GROUPINGS T2 ,
  DS3_USERDATA.SU_SAMPLES T3 ,
  DS3_USERDATA.SU_CLASSIFICATION_RULES T5 ,
  DS3_USERDATA.SU_ANALYSIS_LAYERS T6 ,
  DS3_USERDATA.SU_CHARTS T7,
  DS3_USERDATA.IC50_NEW_RESULTS_SUMMARY T8,
  c2c.ADC R,
  DS3_USERDATA.ADC_CONJUGATE_VW S,
DS3_USERDATA.SU_PLATES P
WHERE T1.LAYER_ID    = T6.ID
AND T1.RULE_ID       = T5.ID
AND T1.GROUP_ID      = T2.ID
AND T2.SAMPLE_ID  = T3.ID
AND T7.RESULT_ID     = T1.ID
AND R.BIOREG_ID=substr(T3.display_name,1,10)
AND R.BIOREG_ID=S.BIOREG_ID(+)
AND P.PLATE_SET=T2.PLATE_SET
AND P.EXPERIMENT_ID=T2.EXPERIMENT_ID
AND T3.DISPLAY_NAME = T8.ID
AND T2.EXPERIMENT_ID=T8.EXPERIMENT_ID
AND P.PLATE_NUMBER=T8.PLATE_NUMBER
AND T2.EXPERIMENT_ID=?)
order by PLATE_NO, ID


_DOTSPLIT_Well Results:NORMAL,
select
p.plate_number,
p.name plate_name,
s.display_name,
round(ws.conc,5) conc,
ws.conc_unit,
wl.name layer,
wr.value result,
CASE wr.status
    WHEN 1
    THEN 'VALIDATED'
    WHEN 2
    THEN 'INVALIDATED'
    WHEN 3
    THEN 'PUBLISHED'
    ELSE 'NOT VALIDATED'
  END VALIDATED
from ds3_userdata.su_well_results wr
join ds3_userdata.su_well_layers wl on wl.id=wr.layer_id
join ds3_userdata.su_wells w on w.id=wr.well_id
join ds3_userdata.su_plates p on p.id=w.plate_id
join ds3_userdata.su_well_samples ws on ws.well_id=w.id
join ds3_userdata.su_samples s on s.id=ws.sample_id
where s.display_name!='None' and WL.EXPERIMENT_ID=?
order by wl.name,p.plate_number, w.rowval, w.colval
