SELECT 
    a.QUERY_ID || a.PROJECT_ID || a.FORM_ID ID, 
    a.QUERY_ID,
    a.ISID,
    a.PROJECT_ID,
    a.FORM_ID,
    a.NAME AS USER_QUERY_NAME,
    a.LAST_RUN,
    a.FORM_VERSION,
    a.LAST_RESULT_COUNT,
    a.LIST_TABLE_NAME,
    a.QUERY_TYPE,
    a.SQL,
    a.FORM_DOMAIN,

    b.FORM_TYPE,
    b.PARENT_PROJECT_ID,
    b.PARENT_FORM_ID,
    b.NAME AS PROJECT_FORMS_NAME,
    b.CURRENT_VERSION,

    c.PROJECT_ID AS PROJECTS_PROJECT_ID,
    c.PROJECT_TYPE,
    c.DESCRIPTION AS PROJECTS_DESCRIPTION
FROM 
    DS3_APPDATA.USER_QUERIES a
LEFT JOIN 
    DS3_APPDATA.PROJECT_FORMS b 
    ON a.FORM_ID = b.FORM_ID
    AND a.PROJECT_ID = b.PROJECT_ID
LEFT JOIN 
    DS3_APPDATA.PROJECTS c 
    ON a.PROJECT_ID = c.PROJECT_ID
ORDER BY 
    a.LAST_RUN, a.ISID
