WITH t AS
    (SELECT DISTINCT
       to_number(a.experiment_id) AS experiment_id,
       a.created_date,
       b.slope,
       b.ic50,
       b.min,
       b.max,
       b.z_prime,
       b.plate_number,
       b.high_avg,
       b.low_avg,
       c.passage,
       c.substrate_lot,
       c.cofactor_lot,
       c.antibody_lot,
       c.reagent_lot,
       c.cell_line,
       c.assay_type,
       to_number(c.cells_well) AS cells_well,
       to_number(c.fbs_conc) AS fbs_conc,
       to_number(c.duration_tx_hr) AS time_hr,
       substr(d.formatted_batch_id, 1, 10) AS formatted_id,
       d.supplier_ref,
       c.project_name_ro,
       d.formatted_batch_id,
       to_number(c.n_replicate) AS n,
       CASE
           WHEN c.protocol_id IN (
                                    544,
                                    543,
                                    542) THEN NULL
           ELSE b.ic90
       END AS ic90,
       b.r2,
       b.compound_status,
       b.classification
     FROM studies_summary a
     INNER JOIN ic50_results_summary b ON a.experiment_id = b.experiment_id
     INNER JOIN ic50_exp_info c ON b.experiment_id = c.experiment_id
     INNER JOIN c$pinpoint.reg_batches d ON b.id = d.formatted_batch_id
     WHERE project_name_ro='SMARCA2'
       AND c.protocol_id IN (
                               341,
                               361,
                               402,
                               421,
                               544,
                               543,
                               542))
  SELECT
    experiment_id,
    created_date,
    slope,
    ic50,
    MIN,
    MAX,
    round(avg(z_prime), 4) AS z_prime,
    plate_number,
    low_avg,
    high_avg,
    passage,
    substrate_lot,
    cofactor_lot,
    antibody_lot,
    reagent_lot,
    cell_line,
    assay_type,
    cells_well,
    fbs_conc,
    time_hr,
    formatted_id,
    supplier_ref,
    project_name_ro,
    formatted_batch_id,
    n,
    ic90,
    r2,
    compound_status,
    classification
  FROM t
  GROUP BY
    experiment_id,
    created_date,
    slope,
    ic50,
    MIN,
    MAX,
    plate_number,
    low_avg,
    high_avg,
    passage,
    substrate_lot,
    cofactor_lot,
    antibody_lot,
    reagent_lot,
    cell_line,
    assay_type,
    cells_well,
    fbs_conc,
    time_hr,
    formatted_id,
    supplier_ref,
    project_name_ro,
    formatted_batch_id,
    n,
    ic90,
    r2,
    compound_status,
    classification
