SELECT 
    x01_formatted_id,
	MIN(IC50_ZR75_1) as IC50_ZR75_1,
    MIN(IC50_NM_ZR75_1) as IC50_NM_ZR75_1,
    max(N_IC50_ZR75_1) as N_IC50_ZR75_1,
    max(SPAN_ZR75_1) as SPAN_ZR75_1,
	max(SD_IC50_ZR75_1) as SD_IC50_ZR75_1,
    max(SD_IC50_NM_ZR75_1) as SD_IC50_NM_ZR75_1,
	
	MIN(IC50_HiBit) as IC50_HiBit,
    MIN(IC50_NM_HiBit) as IC50_NM_HiBit,
    max(N_IC50_HiBit) as N_IC50_HiBit,
	max(Dmax_HiBit) as Dmax_HiBit,
    max(SPAN_HiBit) as SPAN_HiBit,
	max(SD_IC50_HiBit) as SD_IC50_HiBit,
    max(SD_IC50_NM_HiBit) as SD_IC50_NM_HiBit,
	
	MIN(IC50_HiBitH) as IC50_HiBitH,
    MIN(IC50_NM_HiBitH) as IC50_NM_HiBitH,
    max(N_IC50_HiBitH) as N_IC50_HiBitH,
	max(Dmax_HiBitH) as Dmax_HiBitH,
    max(SPAN_HiBitH) as SPAN_HiBitH,
	max(SD_IC50_HiBitH) as SD_IC50_HiBitH,
    max(SD_IC50_NM_HiBitH) as SD_IC50_NM_HiBitH,
	
	MIN(IC50_HiBitPlasmaH) as IC50_HiBitPlasmaH,
    MIN(IC50_NM_HiBitPlasmaH) as IC50_NM_HiBitPlasmaH,
    max(N_IC50_HiBitPlasmaH) as N_IC50_HiBitPlasmaH,
	max(Dmax_HiBitPlasmaH) as Dmax_HiBitPlasmaH,
    max(SPAN_HiBitPlasmaH) as SPAN_HiBitPlasmaH,
	max(SD_IC50_HiBitPlasmaH) as SD_IC50_HiBitPlasmaH,
    max(SD_IC50_NM_HiBitPlasmaH) as SD_IC50_NM_HiBitPlasmaH,
	
	MIN(IC50_HiBitPlasma) as IC50_HiBitPlasma,
    MIN(IC50_NM_HiBitPlasma) as IC50_NM_HiBitPlasma,
    max(N_IC50_HiBitPlasma) as N_IC50_HiBitPlasma,
	max(Dmax_HiBitPlasma) as Dmax_HiBitPlasma,
    max(SPAN_HiBitPlasma) as SPAN_HiBitPlasma,
	max(SD_IC50_HiBitPlasma) as SD_IC50_HiBitPlasma,
    max(SD_IC50_NM_HiBitPlasma) as SD_IC50_NM_HiBitPlasma,
	
	MIN(IC50_ICW_ZR75_1) as IC50_ICW_ZR75_1,
    MIN(IC50_NM_ICW_ZR75_1) as IC50_NM_ICW_ZR75_1,
    max(N_IC50_ICW_ZR75_1) as N_IC50_ICW_ZR75_1,
	
    max(IC10_ICW_ZR75_1) as IC10_ICW_ZR75_1,
    max(IC10_NM_ICW_ZR75_1) as IC10_NM_ICW_ZR75_1,
 
    max(SPAN_ICW_ZR75_1) as SPAN_ICW_ZR75_1,
    
	max(SD_IC50_ICW_ZR75_1) as SD_IC50_ICW_ZR75_1,
    max(SD_IC50_NM_ICW_ZR75_1) as SD_IC50_NM_ICW_ZR75_1,
	
    max(SD_IC10_ICW_ZR75_1) as SD_IC10_ICW_ZR75_1,
    max(SD_IC10_NM_ICW_ZR75_1) as SD_IC10_NM_ICW_ZR75_1,
	
	MIN(IC50_NM_KAT6A) as IC50_NM_KAT6A,
    max(N_IC50_KAT6A) as N_IC50_KAT6A,
    max(SPAN_KAT6A) as SPAN_KAT6A,
    max(PERCENT_INH_KAT6A) as PERCENT_INH_KAT6A,
    max(SD_IC50_NM_KAT6A) as SD_IC50_NM_KAT6A,
    
	MIN(IC50_NM_KAT6B) as IC50_NM_KAT6B,
    max(N_IC50_KAT6B) as N_IC50_KAT6B,
	max(SPAN_KAT6B) as SPAN_KAT6B,
    max(PERCENT_INH_KAT6B) as PERCENT_INH_KAT6B,
    max(SD_IC50_NM_KAT6B) as SD_IC50_NM_KAT6B,
   
    MIN(IC50_NM_KAT7) as IC50_NM_KAT7,
    max(N_IC50_KAT7) as N_IC50_KAT7,
	max(SPAN_KAT7) as SPAN_KAT7,
    max(PERCENT_INH_KAT7) as PERCENT_INH_KAT7,
    max(SD_IC50_NM_KAT7) as SD_IC50_NM_KAT7,

    MIN(IC50_NM_KAT8) as IC50_NM_KAT8,
    max(N_IC50_KAT8) as N_IC50_KAT8,
	max(SPAN_KAT8) as SPAN_KAT8,
    max(PERCENT_INH_KAT8) as PERCENT_INH_KAT8,
    max(SD_IC50_NM_KAT8) as SD_IC50_NM_KAT8,

    MIN(IC50_NM_KAT5) as IC50_NM_KAT5,
    max(N_IC50_KAT5) as N_IC50_KAT5,
	max(SPAN_KAT5) as SPAN_KAT5,
    max(PERCENT_INH_KAT5) as PERCENT_INH_KAT5,
    max(SD_IC50_NM_KAT5) as SD_IC50_NM_KAT5,
  	case  WHEN MAX(CS_IC50_ZR75_1) = 2     THEN
            ''
        WHEN MAX(CS_IC50_ZR75_1) = 1     THEN
           '>'
		WHEN Min(CS_IC50_ZR75_1) = 0     THEN
           '<' end CS_IC50_ZR75_1,
	case WHEN MAX(CS_IC50_HiBit) = 2     THEN
            ''
        WHEN MAX(CS_IC50_HiBit) = 1     THEN
           '>'
		WHEN Min(CS_IC50_HiBit) = 0     THEN
           '<' end CS_IC50_HiBit,
		   
	case WHEN MAX(CS_IC50_HiBitPlasma) = 2     THEN
            ''
        WHEN MAX(CS_IC50_HiBitPlasma) = 1     THEN
           '>'
		WHEN Min(CS_IC50_HiBitPlasma) = 0     THEN
           '<' end CS_IC50_HiBitPlasma, 
		   
		   case WHEN MAX(CS_IC50_HiBitH) = 2     THEN
            ''
        WHEN MAX(CS_IC50_HiBitH) = 1     THEN
           '>'
		WHEN Min(CS_IC50_HiBitH) = 0     THEN
           '<' end CS_IC50_HiBitH, 

		     case WHEN MAX(CS_IC50_HiBitPlasmaH) = 2     THEN
            ''
        WHEN MAX(CS_IC50_HiBitPlasmaH) = 1     THEN
           '>'
		WHEN Min(CS_IC50_HiBitPlasmaH) = 0     THEN
           '<' end CS_IC50_HiBitPlasmaH, 
		   
	
case WHEN MAX(CS_IC50_ICW_ZR75_1) = 2     THEN
            ''
        WHEN MAX(CS_IC50_ICW_ZR75_1) = 1     THEN
           '>'
		WHEN Min(CS_IC50_ICW_ZR75_1) = 0     THEN
           '<' end CS_IC50_ICW_ZR75_1,
	case WHEN MAX(CS_IC50_NM_KAT6A) = 2     THEN
            ''
        WHEN MAX(CS_IC50_NM_KAT6A) = 1     THEN
           '>'
		WHEN Min(CS_IC50_NM_KAT6A) = 0     THEN
           '<' end CS_IC50_NM_KAT6A,
	case WHEN MAX(CS_IC50_NM_KAT6B) = 2     THEN
            ''
        WHEN MAX(CS_IC50_NM_KAT6B) = 1     THEN
           '>'
		WHEN Min(CS_IC50_NM_KAT6B) = 0     THEN
           '<' end CS_IC50_NM_KAT6B,
	case WHEN MAX(CS_IC50_NM_KAT7) = 2     THEN
            ''
        WHEN MAX(CS_IC50_NM_KAT7) = 1     THEN
           '>'
		WHEN Min(CS_IC50_NM_KAT7) = 0     THEN
           '<' end CS_IC50_NM_KAT7,
	case WHEN MAX(CS_IC50_NM_KAT8) = 2     THEN
            ''
        WHEN MAX(CS_IC50_NM_KAT8) = 1     THEN
           '>'
		WHEN Min(CS_IC50_NM_KAT8) = 0     THEN
           '<' end CS_IC50_NM_KAT8,
	case WHEN MAX(CS_IC50_NM_KAT5) = 2     THEN
            ''
        WHEN MAX(CS_IC50_NM_KAT5) = 1     THEN
           '>'
		WHEN Min(CS_IC50_NM_KAT5) = 0     THEN
           '<' end CS_IC50_NM_KAT5,
	max(LE) as LE,
    max(LLE) as LLE

	FROM (
		SELECT     
		t0.formatted_id AS x01_formatted_id, 

		CASE WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.p
             WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NOT NULL THEN T10.p		
		     WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NULL THEN T10.R END IC50_ZR75_1,
        CASE WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.p*1000
             WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NOT NULL THEN T10.p*1000		
		     WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NULL THEN T10.R*1000 END IC50_NM_ZR75_1,
        CASE WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' THEN T13.D END N_IC50_ZR75_1,
		CASE WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NOT NULL THEN 2
             WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NULL  AND T10.R IS NOT NULL and T10.compound_status='>' THEN 1
WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NULL  AND T10.R IS NOT NULL and T10.compound_status='<' THEN 0			 END CS_IC50_ZR75_1,
		
		CASE WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.pspan
             WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NOT NULL THEN T10.pspan		
		     WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NULL THEN T10.pspan END SPAN_ZR75_1,
		
		CASE WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.SD
             WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NOT NULL THEN T10.SD		
		     WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NULL THEN T10.SD END SD_IC50_ZR75_1,
		CASE WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.SD*1000
             WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NOT NULL THEN T10.SD*1000		
		     WHEN T10.assay_type = 'CellTiter-Glo' AND T10.cell_line = 'ZR75-1' AND T10.P IS NULL THEN T10.SD*1000 END SD_IC50_NM_ZR75_1,
			 
		CASE WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.p
             WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL THEN T10.p		
		     WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NULL THEN T10.R END IC50_HiBit,
        CASE WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.p*1000
             WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL THEN T10.p*1000		
		     WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NULL THEN T10.R*1000 END IC50_NM_HiBit,
        CASE WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' THEN T13.D END N_IC50_HiBit,
		CASE WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL THEN 2
             WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NULL  AND T10.R IS NOT NULL and T10.compound_status='>' THEN 1
WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NULL  AND T10.R IS NOT NULL and T10.compound_status='<' THEN 0			 END CS_IC50_HiBit,
		CASE WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN 100-T10.MIN
             WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL THEN 100-T10.MIN		
		     WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NULL THEN 100-T10.MINR END Dmax_HiBit,
			 
		CASE WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.pspan
             WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL THEN T10.pspan		
		     WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NULL THEN T10.pspan END SPAN_HiBit,
		
		CASE WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.SD
             WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL THEN T10.SD		
		     WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NULL THEN T10.SD END SD_IC50_HiBit,
		CASE WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.SD*1000
             WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL THEN T10.SD*1000		
		     WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NULL THEN T10.SD*1000 END SD_IC50_NM_HiBit,
			 
		CASE WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.p
             WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL THEN T10.p		
		     WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NULL THEN T10.R END IC50_HiBitH,
        CASE WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.p*1000
             WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL THEN T10.p*1000		
		     WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NULL THEN T10.R*1000 END IC50_NM_HiBitH,
        CASE WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' THEN T13.D END N_IC50_HiBitH,
		CASE WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL THEN 2
             WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NULL  AND T10.R IS NOT NULL and T10.compound_status='>' THEN 1
WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NULL  AND T10.R IS NOT NULL and T10.compound_status='<' THEN 0	 END CS_IC50_HiBitH,
		CASE WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN 100-T10.MIN
             WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL THEN 100-T10.MIN		
		     WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NULL THEN 100-T10.MINR END Dmax_HiBitH,
			 
		CASE WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.pspan
             WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL THEN T10.pspan		
		     WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NULL THEN T10.pspan END SPAN_HiBitH,
		
		CASE WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.SD
             WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL THEN T10.SD		
		     WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NULL THEN T10.SD END SD_IC50_HiBitH,
		CASE WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.SD*1000
             WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL THEN T10.SD*1000		
		     WHEN T10.assay_type = 'HiBit' AND T10.cell_line = 'Hela' AND T10.P IS NULL THEN T10.SD*1000 END SD_IC50_NM_HiBitH,
			 
		CASE WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.p
             WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL THEN T10.p		
		     WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NULL THEN T10.R END IC50_HiBitPlasma,
        CASE WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.p*1000
             WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL THEN T10.p*1000		
		     WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NULL THEN T10.R*1000 END IC50_NM_HiBitPlasma,
        CASE WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' THEN T13.D END N_IC50_HiBitPlasma,
		CASE WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL THEN 2
             WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NULL  AND T10.R IS NOT NULL and T10.compound_status='>' THEN 1
 WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NULL  AND T10.R IS NOT NULL and T10.compound_status='<' THEN 0			 END CS_IC50_HiBitPlasma,
		CASE WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN 100-T10.MIN
             WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL THEN 100-T10.MIN		
		     WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NULL THEN 100-T10.MINR END Dmax_HiBitPlasma,
			 
		CASE WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.pspan
             WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL THEN T10.pspan		
		     WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NULL THEN T10.pspan END SPAN_HiBitPlasma,
		
		CASE WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.SD
             WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL THEN T10.SD		
		     WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NULL THEN T10.SD END SD_IC50_HiBitPlasma,
		CASE WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.SD*1000
             WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NOT NULL THEN T10.SD*1000		
		     WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela-HiBit-KAT6A' AND T10.P IS NULL THEN T10.SD*1000 END SD_IC50_NM_HiBitPlasma,
			 
		CASE WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.p
             WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL THEN T10.p		
		     WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NULL THEN T10.R END IC50_HiBitPlasmaH,
        CASE WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.p*1000
             WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL THEN T10.p*1000		
		     WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NULL THEN T10.R*1000 END IC50_NM_HiBitPlasmaH,
        CASE WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' THEN T13.D END N_IC50_HiBitPlasmaH,
		CASE WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL THEN 2
             WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NULL  AND T10.R IS NOT NULL and T10.compound_status='>' THEN 1
 WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NULL  AND T10.R IS NOT NULL and T10.compound_status='<' THEN 0		 END CS_IC50_HiBitPlasmaH,
		CASE WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN 100-T10.MIN
             WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL THEN 100-T10.MIN		
		     WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NULL THEN 100-T10.MINR END Dmax_HiBitPlasmaH,
			 
		CASE WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.pspan
             WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL THEN T10.pspan		
		     WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NULL THEN T10.pspan END SPAN_HiBitPlasmaH,
		
		CASE WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.SD
             WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL THEN T10.SD		
		     WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NULL THEN T10.SD END SD_IC50_HiBitPlasmaH,
		CASE WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL AND T10.R IS NOT NULL THEN T10.SD*1000
             WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NOT NULL THEN T10.SD*1000		
		     WHEN T10.assay_type = 'HiBit Plasma' AND T10.cell_line = 'Hela' AND T10.P IS NULL THEN T10.SD*1000 END SD_IC50_NM_HiBitPlasmaH,
			 
		CASE WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL AND T11.R IS NOT NULL THEN T11.p
             WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL THEN T11.p		
		     WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NULL THEN T11.R END IC50_ICW_ZR75_1,
        CASE WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL AND T11.R IS NOT NULL THEN T11.p*1000
             WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL THEN T11.p*1000		
		     WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NULL THEN T11.R*1000 END IC50_NM_ICW_ZR75_1,
        CASE WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' THEN T14.D END N_IC50_ICW_ZR75_1,
		CASE WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL THEN 2
             WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NULL  AND T11.R IS NOT NULL and T11.compound_status='>' THEN 1
 WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NULL  AND T11.R IS NOT NULL and T11.compound_status='<' THEN 0			 END CS_IC50_ICW_ZR75_1,
				 
		CASE WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL AND T11.R IS NOT NULL THEN T11.p10 
             WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL THEN T11.p10 		
		     WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NULL THEN T11.p10 END IC10_ICW_ZR75_1,
        CASE WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL AND T11.R IS NOT NULL THEN T11.p10*1000
             WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL THEN T11.p10*1000		
		     WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NULL THEN T11.p10*1000 END IC10_NM_ICW_ZR75_1,
			 
		CASE WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL AND T11.R IS NOT NULL THEN T11.pspan
             WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL THEN T11.pspan		
		     WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NULL THEN T11.pspan END SPAN_ICW_ZR75_1,
			 
		CASE WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL AND T11.R IS NOT NULL THEN T11.SD 
             WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL THEN T11.SD 		
		     WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NULL THEN T11.SD END SD_IC50_ICW_ZR75_1,
        CASE WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL AND T11.R IS NOT NULL THEN T11.SD*1000
             WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL THEN T11.SD*1000		
		     WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NULL THEN T11.SD*1000 END SD_IC50_NM_ICW_ZR75_1,
			 
		CASE WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL AND T11.R IS NOT NULL THEN T11.SD10 
             WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL THEN T11.SD10 		
		     WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NULL THEN T11.SD10 END SD_IC10_ICW_ZR75_1,
        CASE WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL AND T11.R IS NOT NULL THEN T11.SD10*1000
             WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NOT NULL THEN T11.SD10*1000		
		     WHEN T11.assay_type = 'ICW' AND T11.cell_line = 'ZR75-1' AND T11.P IS NULL THEN T11.SD10*1000 END SD_IC10_NM_ICW_ZR75_1,
		
		
		CASE WHEN T12.TARGET='KAT6A' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN T12.p
             WHEN T12.TARGET='KAT6A' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN T12.p		
		     WHEN T12.TARGET='KAT6A' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN T12.R END IC50_NM_KAT6A,
        CASE WHEN T12.TARGET='KAT6A' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' THEN T15.D END N_IC50_KAT6A,
			CASE WHEN T12.TARGET='KAT6A' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN 2
		     WHEN T12.TARGET='KAT6A' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL AND T12.R IS NOT NULL and T12.compound_status='>' THEN 1
WHEN T12.TARGET='KAT6A' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL AND T12.R IS NOT NULL and T12.compound_status='<' THEN 0			 END CS_IC50_NM_KAT6A,
	CASE WHEN T12.TARGET='KAT6A' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN T12.pspan 
		     WHEN T12.TARGET='KAT6A' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN T12.pspan 
			 WHEN T12.TARGET='KAT6A' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN T12.pspan END SPAN_KAT6A,
        CASE WHEN T12.TARGET='KAT6A' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN 100-T12.pinh 
		     WHEN T12.TARGET='KAT6A' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN 100-T12.pinh 
			 WHEN T12.TARGET='KAT6A' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN 100-T12.pinh END PERCENT_INH_KAT6A,
		CASE WHEN T12.TARGET='KAT6A' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN T12.SD 
		     WHEN T12.TARGET='KAT6A' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN T12.SD 
			 WHEN T12.TARGET='KAT6A' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN T12.SD END SD_IC50_NM_KAT6A,
			 
		CASE WHEN T12.TARGET='KAT6B' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN T12.p
             WHEN T12.TARGET='KAT6B' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN T12.p		
		     WHEN T12.TARGET='KAT6B' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN T12.R END IC50_NM_KAT6B,
        CASE WHEN T12.TARGET='KAT6B' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' THEN T15.D END N_IC50_KAT6B,
		CASE WHEN T12.TARGET='KAT6B' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN 2 
		     WHEN T12.TARGET='KAT6B' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL AND T12.R IS NOT NULL and T12.compound_status='>' THEN 1
WHEN T12.TARGET='KAT6B' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL AND T12.R IS NOT NULL and T12.compound_status='<' THEN 0			 END CS_IC50_NM_KAT6B,
		CASE WHEN T12.TARGET='KAT6B' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN T12.pspan 
		     WHEN T12.TARGET='KAT6B' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN T12.pspan 
			 WHEN T12.TARGET='KAT6B' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN T12.pspan END SPAN_KAT6B,
        CASE WHEN T12.TARGET='KAT6B' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN 100-T12.pinh 
		     WHEN T12.TARGET='KAT6B' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN 100-T12.pinh 
			 WHEN T12.TARGET='KAT6B' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN 100-T12.pinh END PERCENT_INH_KAT6B,
		CASE WHEN T12.TARGET='KAT6B' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN T12.SD 
		     WHEN T12.TARGET='KAT6B' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN T12.SD 
			 WHEN T12.TARGET='KAT6B' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN T12.SD END SD_IC50_NM_KAT6B,
			 
		CASE WHEN T12.TARGET='KAT7' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN T12.p
             WHEN T12.TARGET='KAT7' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN T12.p		
		     WHEN T12.TARGET='KAT7' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN T12.R END IC50_NM_KAT7,
        CASE WHEN T12.TARGET='KAT7' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' THEN T15.D END N_IC50_KAT7,
		CASE WHEN T12.TARGET='KAT7' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN 2
		     WHEN T12.TARGET='KAT7' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL AND T12.R IS NOT NULL and T12.compound_status='>' THEN 1
WHEN T12.TARGET='KAT7' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL AND T12.R IS NOT NULL and T12.compound_status='<' THEN 0			 END CS_IC50_NM_KAT7,
		CASE WHEN T12.TARGET='KAT7' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN T12.pspan 
		     WHEN T12.TARGET='KAT7' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN T12.pspan 
			 WHEN T12.TARGET='KAT7' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN T12.pspan END SPAN_KAT7,
        CASE WHEN T12.TARGET='KAT7' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN 100-T12.pinh 
		     WHEN T12.TARGET='KAT7' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN 100-T12.pinh 
			 WHEN T12.TARGET='KAT7' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN 100-T12.pinh END PERCENT_INH_KAT7,
		CASE WHEN T12.TARGET='KAT7' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN T12.SD 
		     WHEN T12.TARGET='KAT7' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN T12.SD 
			 WHEN T12.TARGET='KAT7' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN T12.SD END SD_IC50_NM_KAT7,
			 
		CASE WHEN T12.TARGET='KAT8' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN T12.p
             WHEN T12.TARGET='KAT8' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN T12.p		
		     WHEN T12.TARGET='KAT8' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN T12.R END IC50_NM_KAT8,
        CASE WHEN T12.TARGET='KAT8' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' THEN T15.D END N_IC50_KAT8,
			CASE WHEN T12.TARGET='KAT8' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN 2 
		     WHEN T12.TARGET='KAT8' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL AND T12.R IS NOT NULL and T12.compound_status='>' THEN 1
WHEN T12.TARGET='KAT8' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL AND T12.R IS NOT NULL and T12.compound_status='<' THEN 0			 END CS_IC50_NM_KAT8,
		CASE WHEN T12.TARGET='KAT8' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN T12.pspan 
		     WHEN T12.TARGET='KAT8' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN T12.pspan 
			 WHEN T12.TARGET='KAT8' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN T12.pspan END SPAN_KAT8,
        CASE WHEN T12.TARGET='KAT8' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN 100-T12.pinh 
		     WHEN T12.TARGET='KAT8' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN 100-T12.pinh 
			 WHEN T12.TARGET='KAT8' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN 100-T12.pinh END PERCENT_INH_KAT8,
		CASE WHEN T12.TARGET='KAT8' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN T12.SD 
		     WHEN T12.TARGET='KAT8' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN T12.SD 
			 WHEN T12.TARGET='KAT8' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN T12.SD END SD_IC50_NM_KAT8,

			 
		CASE WHEN T12.TARGET='KAT5' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN T12.p
             WHEN T12.TARGET='KAT5' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN T12.p		
		     WHEN T12.TARGET='KAT5' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN T12.R END IC50_NM_KAT5,
        CASE WHEN T12.TARGET='KAT5' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' THEN T15.D END N_IC50_KAT5,
		CASE WHEN T12.TARGET='KAT5' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN 2 
		     WHEN T12.TARGET='KAT5' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL AND T12.R IS NOT NULL and T12.compound_status='>' THEN 1
WHEN T12.TARGET='KAT5' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL AND T12.R IS NOT NULL and T12.compound_status='<' THEN 0			 END CS_IC50_NM_KAT5,
		CASE WHEN T12.TARGET='KAT5' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN T12.pspan 
		     WHEN T12.TARGET='KAT5' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN T12.pspan 
			 WHEN T12.TARGET='KAT5' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN T12.pspan END SPAN_KAT5,
        CASE WHEN T12.TARGET='KAT5' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN 100-T12.pinh 
		     WHEN T12.TARGET='KAT5' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN 100-T12.pinh 
			 WHEN T12.TARGET='KAT5' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN 100-T12.pinh END PERCENT_INH_KAT5,
		CASE WHEN T12.TARGET='KAT5' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL AND T12.R IS NOT NULL THEN T12.SD 
		     WHEN T12.TARGET='KAT5' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NOT NULL THEN T12.SD 
			 WHEN T12.TARGET='KAT5' AND T12.COFACTOR='Acetyl-CoA' AND T12.COFACTOR_CONC='3 uM' AND T12.P IS NULL THEN T12.SD END SD_IC50_NM_KAT5,

	
		T2.LIGAND_EFFICIENCY as LE,
        T2.LIPOPHILLIC_EFFICIENCY as LLE
		
		FROM
		DS3_USERDATA.KAT6A_REG_DATA_VW T0
	LEFT JOIN 
	(SELECT A.FORMATTED_ID,
	A.P,
	A.T,
	A.C,
	B.HAC,
	(1.4*(-log(10,(A.P*(POWER(10,-9))))/B.HAC)) AS LIGAND_EFFICIENCY,
	(-log(10,(A.P*POWER(10,-9)))) AS PIC50,
	((-log(10,(A.P*POWER(10,-9)))) - B.XLOGP) AS LIPOPHILLIC_EFFICIENCY
	FROM
	((SELECT 
	FORMATTED_ID, 
	POWER(10, AVG(LOG(10, IC50_NM))) as p, 
	TARGET as t,
	COUNT(TARGET) as c
	FROM DS3_USERDATA.KAT6A_TRFRET_REGISTRY_SUMMARY
	WHERE TARGET = 'KAT6A'
	AND TARGET IS NOT NULL
	AND IC50_NM > 0
	GROUP BY FORMATTED_ID, TARGET)A
	LEFT JOIN 
	DS3_USERDATA.CALC_PHYS_PROPERTIES B
	ON A.FORMATTED_ID = B.CP_ID)
	ORDER BY FORMATTED_ID)T2
	ON T0.FORMATTED_ID = T2.FORMATTED_ID	
		
	LEFT JOIN 
	(SELECT * FROM ((SELECT 
	FORMATTED_ID,
	power(10,AVG(log(10,CASE WHEN ic50 > 0 THEN ic50 ELSE NULL END))) AS p,
	NULL AS R,
	power(10,AVG(log(10,CASE WHEN span > 0 THEN span ELSE NULL END))) AS pspan,
	POWER(10, AVG(LOG(10,CASE WHEN MIN > 0 THEN MIN ELSE NULL END))) AS MIN,
	NULL AS MINR,
	STDDEV(ic50) AS SD,
	STDDEV(span) AS SDspan,
	assay_type ,
	cell_line,
	compound_status,
	COUNT(FORMATTED_ID) as c
	FROM DS3_USERDATA.KAT6A_REGISTRY_SUMMARY
	WHERE COMPOUND_STATUS IS NULL
	GROUP BY FORMATTED_ID, assay_type,CELL_LINE,compound_status) 
	
	UNION ALL
	
	(SELECT 
	FORMATTED_ID,
	NULL AS P,
	MAX(ic50) AS r,
	power(10,AVG(log(10,CASE WHEN span > 0 THEN span ELSE NULL END))) AS pspan,
	NULL AS MIN,
	POWER(10, AVG(LOG(10,CASE WHEN MIN > 0 THEN MIN ELSE NULL END))) AS MINR,
	STDDEV(ic50) AS SD,
	STDDEV(span) AS SDspan,
	assay_type ,
	cell_line,
	compound_status,
	COUNT(FORMATTED_ID) as c
	FROM DS3_USERDATA.KAT6A_REGISTRY_SUMMARY
	WHERE COMPOUND_STATUS IS NOT NULL
	GROUP BY FORMATTED_ID, assay_type,CELL_LINE,compound_status))) T10
	ON T0.FORMATTED_ID = T10.FORMATTED_ID
	
	LEFT JOIN 
	
	(SELECT 
	FORMATTED_ID,
	assay_type ,
	cell_line,
	COUNT(FORMATTED_ID) as D
	FROM DS3_USERDATA.KAT6A_REGISTRY_SUMMARY
	GROUP BY FORMATTED_ID, assay_type,CELL_LINE) T13
	ON T0.FORMATTED_ID = T13.FORMATTED_ID AND T10.assay_type=T13.assay_type AND T10.CELL_LINE=T13.CELL_LINE

	LEFT JOIN 
	(SELECT * FROM ((SELECT 
	FORMATTED_ID,
	power(10,AVG(log(10,CASE WHEN ic50 > 0 THEN ic50 ELSE NULL END))) AS p,
	NULL AS R,
	power(10,AVG(log(10,CASE WHEN IC10 > 0 THEN IC10 ELSE NULL END))) AS p10,
	power(10,AVG(log(10,CASE WHEN span > 0 THEN span ELSE NULL END))) AS pspan,
	STDDEV(ic50) AS SD,
	STDDEV(ic10) AS SD10,
	STDDEV(span) AS SDspan,
	assay_type ,
	cell_line,
	compound_status,
	COUNT(FORMATTED_ID) as c
	FROM DS3_USERDATA.KAT6A_ICW_REGISTRY_SUMMARY
	WHERE COMPOUND_STATUS IS NULL
	GROUP BY FORMATTED_ID, assay_type, cell_line,compound_status) 
	
	UNION ALL
	
	(SELECT 
	FORMATTED_ID,
	NULL AS P,
	MAX(ic50) AS r,
	power(10,AVG(log(10,CASE WHEN IC10 > 0 THEN IC10 ELSE NULL END))) AS p10,
	power(10,AVG(log(10,CASE WHEN span > 0 THEN span ELSE NULL END))) AS pspan,
	STDDEV(ic50) AS SD,
	STDDEV(ic10) AS SD10,
	STDDEV(span) AS SDspan,
	assay_type ,
	cell_line,
	compound_status,
	COUNT(FORMATTED_ID) as c
	FROM DS3_USERDATA.KAT6A_ICW_REGISTRY_SUMMARY
	WHERE COMPOUND_STATUS IS NOT NULL
	GROUP BY FORMATTED_ID, assay_type, cell_line,compound_status))) T11
	ON T0.FORMATTED_ID = T11.FORMATTED_ID
	
	LEFT JOIN 
	
	(SELECT 
	FORMATTED_ID,
	assay_type ,
	cell_line,
	COUNT(FORMATTED_ID) as D
	FROM DS3_USERDATA.KAT6A_ICW_REGISTRY_SUMMARY
	GROUP BY FORMATTED_ID, assay_type, cell_line) T14
	ON T0.FORMATTED_ID = T14.FORMATTED_ID AND T11.assay_type=T14.assay_type AND T11.cell_line=T14.cell_line

	LEFT JOIN 
	(SELECT * FROM ((SELECT 
	FORMATTED_ID,
	POWER(10, AVG(LOG(10,CASE WHEN IC50_NM > 0 THEN IC50_NM ELSE NULL END ))) as p,
    NULL AS R,	
	POWER(10, AVG(LOG(10,CASE WHEN span > 0 THEN span ELSE NULL END ))) as pspan,
	POWER(10, AVG(LOG(10,CASE WHEN percent_inhibition > 0 THEN percent_inhibition ELSE NULL END ))) as pinh,
	STDDEV(ic50_NM) AS SD,
	STDDEV(span) AS SDspan,
	STDDEV(percent_inhibition) AS SDinh,
	TARGET ,
	COFACTOR,
	COFACTOR_CONC,
	Compound_Status,
	COUNT(FORMATTED_ID) as c
	FROM DS3_USERDATA.KAT6A_TRFRET_REGISTRY_SUMMARY
	WHERE COMPOUND_STATUS IS NULL
	GROUP BY FORMATTED_ID, TARGET,compound_status,COFACTOR,COFACTOR_CONC ) 
	
	UNION ALL
	 
	(SELECT 
	FORMATTED_ID,
	NULL AS P,
	MAX(ic50_NM) as r, 
	POWER(10, AVG(LOG(10,CASE WHEN span > 0 THEN span ELSE NULL END ))) as pspan,
	POWER(10, AVG(LOG(10,CASE WHEN percent_inhibition > 0 THEN percent_inhibition ELSE NULL END ))) as pinh,
	STDDEV(ic50_NM) AS SD,
	STDDEV(span) AS SDspan,
	STDDEV(percent_inhibition) AS SDinh,
	TARGET ,
	COFACTOR,
	COFACTOR_CONC,
	Compound_Status,
	COUNT(FORMATTED_ID) as c
	FROM DS3_USERDATA.KAT6A_TRFRET_REGISTRY_SUMMARY
	WHERE COMPOUND_STATUS IS NOT NULL
	GROUP BY FORMATTED_ID, TARGET,compound_status,COFACTOR,COFACTOR_CONC ))) T12
	ON T0.FORMATTED_ID = T12.FORMATTED_ID
	
	LEFT JOIN
	
	(SELECT 
	FORMATTED_ID,
	TARGET ,
	COFACTOR,
	COFACTOR_CONC,
	COUNT(FORMATTED_ID) as D
	FROM DS3_USERDATA.KAT6A_TRFRET_REGISTRY_SUMMARY
	GROUP BY FORMATTED_ID, TARGET,COFACTOR,COFACTOR_CONC ) T15
	ON T0.FORMATTED_ID = T15.FORMATTED_ID AND T12.TARGET =T15.TARGET AND T12.COFACTOR =T15.COFACTOR AND T12.COFACTOR_CONC=T15.COFACTOR_CONC 

	)
GROUP BY x01_formatted_id
